[package]
name = "mcumgr-smp"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Sascha Zenglein <zenglein@gessler.de>"]
description = "An implementation of the smp protocol for microcontrollers in pure rust."
readme = "README.md"
repository = "https://github.com/Gessler-GmbH/smp-rs"
homepage = "https://github.com/Gessler-GmbH/smp-rs"
categories = ["embedded", "development-tools"]
keywords = ["smp", "zephyr", "rtos", "mcumgr"]

[dependencies]
thiserror = "1.0"


ciborium = { version = "0.2", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_bytes = { version = "0.11", optional = true }

base64 = { version = "0.21", optional = true }
crc = { version = "3.0", optional = true }

[features]
default = ["serial", "payload-cbor"]
serial = ["base64", "crc", ]
payload-cbor = ["serde", "serde_bytes", "ciborium"]